create login [asa.sql.workload01] with password = 'Pa55w.rd!12'
create login [asa.sql.workload02] with password = 'Pa55w.rd!12'
create login [asa.sql.import01] with password = 'Pa55w.rd!12'
create login [asa.sql.import02] with password = 'Pa55w.rd!12'
create login [asa.sql.highperf] with password = 'Pa55w.rd!12'
